---
cidr_networks:
  container: "192.168.10.0/24"
  storage: "192.168.11.0/24"
  tunnel: "192.168.12.0/24"

used_ips:
  - "192.168.10.200 192.168.10.254"
  - "192.168.11.200 192.168.11.254"
  - "192.168.12.200 192.168.12.254"

global_overrides:
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
      container_bridge: "br-mgmt"
      container_type: "veth"
      container_interface: "eth0"
      ip_from_q: "container"
      type: "raw"
      group_binds:
        - all_containers
        - hosts
      is_container_address: true
      is_ssh_address: true
    - network:
      container_bridge: "br-vxlan"
      container_type: "veth"
      container_interface: "eth1"
      ip_from_q: "tunnel"
      type: "vxlan"
      range: "1:1000"
      net_name: "vxlan"
      group_binds:
        - neutron_linuxbridge_agent
    - network:
      container_bridge: "br-vlan"
      container_type: "veth"
      container_interface: "eth2"
      host_bind_override: "ens5"
      type: "flat"
      net_name: "flat"
      group_binds:
        - neutron_linuxbridge_agent
    - network:
      container_bridge: "br-storage"
      container_type: "veth"
      container_interface: "eth3"
      ip_from_q: "storage"
      type: "raw"
      group_binds:
        - glance_api
        - cinder_api
        - cinder_volume
        - nova_compute
        - ceph-osd

_infra_hosts: &infra_hosts
  infra0:
    ip: 192.168.10.18
  infra1:
    ip: 192.168.10.17
  infra2:
    ip: 192.168.10.20

_compute_hosts: &compute_hosts
  compute0:
    ip: 192.168.10.22
  compute1:
    ip: 192.168.10.19
  compute2:
    ip: 192.168.10.21

_osd_hosts: &osd_hosts
  osd0:
    ip: 192.168.10.15
  osd1:
    ip: 192.168.10.13
  osd2:
    ip: 192.168.10.16

shared-infra_hosts: *infra_hosts

repo-infra_hosts: *infra_hosts

os-infra_hosts: *infra_hosts

identity_hosts: *infra_hosts

network_hosts: *infra_hosts

compute_hosts: *compute_hosts

storage-infra_hosts: *infra_hosts

storage_hosts: *infra_hosts

ceph-osd_hosts: *osd_hosts

ceph-mon_hosts: *infra_hosts

log_hosts:
  log0:
    ip: 192.168.10.14

haproxy_hosts: *infra_hosts
