heat_template_version: '2016-04-08'

description: >
    OpenStack server

parameters:
    key_name:
        type: string
        description: SSH Key
    image:
        type: string
        description: Image
    networks:
        type: json
        description: Networks
    name:
        type: string
        description: name
resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: "m4.medium"
      image: { get_param: image }
      key_name: { get_param: key_name }
      name: { get_param: name }
      networks: { get_param: networks }
outputs:
  server_id:
    value: { get_resource: server }
  server_ip:
    value: { get_attr: [server, networks, mgmt, 0] }
  server_name:
    value: { get_attr: [server, name] }
