heat_template_version: '2016-04-08'

description: >
    OSD server

resources:
  server:
   type: OS::Nova::Server
   properties:
    name: "osd-%index%"
    image: { get_param: image }
    flavor: "m4.medium"
    key_name: { get_param: sshkey }
    networks: 
      - network: { get_resource: mgmt_net }
      - network: { get_resource: storage_net }
      - network: { get_resource: repl_net }
    user_data:
      str_replace:
        template: |
            #!/bin/sh
            echo "REPLICATION_FACTOR: REPLF" > /root/ceph_replication_factor
          params:
            REPLF: { get_param: ceph_repl_factor }
outputs:
  server_id:
    value: { get_resource: server }
  server_ip:
    value: { get_attr: [server, networks, mgmt_net, 0] }
