
heat_template_version: '2016-04-08'

description: >
    Testing various things

parameters:
    sshkey:
        type: string
        description: Name of an existing key pair
        default: default
        constraints:
          - custom_constraint: nova.keypair
    image:
        type: string
        description: Image ID or image name to use
        default: Ubuntu1604-Latest
        constraints:
          - custom_constraint: glance.image
resources:
    a_dude:
        type: openstack_server.yaml
        properties:
            key_name: { get_param: sshkey }
            image: { get_param: image }
            name: littleGuy
            networks:
                - network: 32657101-c9a1-4016-bea7-c59ed179d73b 
outputs:
    ip:
        description: Should have an IP here
        value: { get_attr: [a_dude, server_ip] }
    id:
        description: Should have an ID here
        value: { get_attr: [a_dude, server_id] }
    for_real:
        description: Data here
        value: { get_attr: [a_dude, first_address] }

